spring.datasource.url=jdbc:h2:mem:countiesdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create
server.port=3000
logging.level.root=INFO
spring.cache.type=caffeine
